export const LOGIN_INIT = "LOGIN_INIT"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const FETCH_NOTES_INIT = "FETCH_NOTES_INIT"
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS"
export const FETCH_NOTES_FAIL = "FETCH_NOTES_FAIL"


export const ADD_NOTES_INIT = "ADD_NOTES_INIT"
export const ADD_NOTES_SUCCESS = "ADD_NOTES_SUCCESS"
export const ADD_NOTES_FAIL = "ADD_NOTES_FAIL"

export const DELETE_NOTES_INIT = "DELETE_NOTES_INIT"
export const DELETE_NOTES_SUCCESS = "DELETE_NOTES_SUCCESS"
export const DELETE_NOTES_FAIL = "DELETE_NOTES_FAIL"

export const CHECK_ERROR = "CHECK_ERROR";
export const CHECK_ERROR_INIT = "CHECK_ERROR_INIT";